name: 'Sync With Upstream'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_master:
    uses: bradh352/sonic-buildimage/.github/workflows/reuse-sync.yml@bradh352/master
    with:
      upstream_repo: "sonic-net/sonic-utilities"
      upstream_branch: "master"
      local_branch: "bradh352/master"
    secrets: inherit
  sync_202411:
    uses: bradh352/sonic-buildimage/.github/workflows/reuse-sync.yml@bradh352/master
    with:
      upstream_repo: "sonic-net/sonic-utilities"
      upstream_branch: "202411"
      local_branch: "bradh352/202411"
    secrets: inherit
